### ISSUE TITLE
Hi, This might frustrate you but if its possible could you implement sideBySide property 

### ISSUE THREAD

**Issue by sonuoommen** [zpaulovics/dateTimeDemo#1]
http://eonasdan.github.io/bootstrap-datetimepicker/Options/

if its not a trouble.

**Comment by zpaulovics** [comment]
Super! Your range picker functionality works fine, but does not handle the SimpleForm horizontal form look and feel. Look at the new version of this demo.

**Comment by zpaulovics** [comment]
Hi,

The SimpleForm horisontal layout should be handled by your template. 

Zolan
